CREATE TABLE payments (
                          id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'Surrogate Key',
                          paypal_order_id VARCHAR(50) NOT NULL UNIQUE COMMENT 'PayPal Orders v2 order id (capture 시 조회 키)',
                          guest_id BIGINT NOT NULL COMMENT '결제/예약 주체 (주문 생성 시 인증 principal에서)',
                          room_id BIGINT NOT NULL,
                          check_in_date DATE NOT NULL,
                          check_out_date DATE NOT NULL,
                          adult_count INT NOT NULL DEFAULT 1 COMMENT '성인 수',
                          child_count INT NOT NULL DEFAULT 0 COMMENT '어린이 수',
                          infant_count INT NOT NULL DEFAULT 0 COMMENT '유아 수',
                          has_pets BOOLEAN NOT NULL DEFAULT FALSE COMMENT '반려동물 동반 여부',
                          krw_total INT NOT NULL COMMENT '원화 총액 (예약 total_price 로 그대로 사용)',
                          paypal_amount DECIMAL(15, 2) NOT NULL COMMENT '실제 PayPal 청구 금액',
                          currency VARCHAR(3) NOT NULL COMMENT '결제 통화 (예: USD)',
                          status VARCHAR(20) NOT NULL COMMENT 'CREATED, CAPTURED, FAILED',
                          reservation_id BIGINT NULL COMMENT 'capture 성공 후 생성된 예약 (그 전엔 NULL)',
                          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                          updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                          FOREIGN KEY (guest_id) REFERENCES members(id),
                          FOREIGN KEY (room_id) REFERENCES rooms(id),
                          FOREIGN KEY (reservation_id) REFERENCES reservations(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
