spring:
  application:
    name: AirDND
  profiles:
    default: local
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    open-in-view: false

server:
  forward-headers-strategy: framework
